export const agnozGallery = [
    "/images/Agnoz C-R/Admin/Dashboard.png",
    "/images/Agnoz C-R/Admin/Dashboard-1.png",
    "/images/Agnoz C-R/Admin/Dashboard-2.png",
    "/images/Agnoz C-R/Admin/Dashboard-3.png",
    "/images/Agnoz C-R/Admin/Dashboard-4.png",
    "/images/Agnoz C-R/Admin/Dashboard-5.png",
    "/images/Agnoz C-R/Admin/Dashboard-6.png",
    "/images/Agnoz C-R/Admin/Details-1.png",
    "/images/Agnoz C-R/Admin/Details.png",
    "/images/Agnoz C-R/Admin/Sign In.png",
    "/images/Agnoz C-R/Admin/Splash Screen.png",

    // Patient Screenshots
    "/images/Agnoz C-R/Patient/17 Payment Method.png",
    "/images/Agnoz C-R/Patient/18 Add New Address.png",
    "/images/Agnoz C-R/Patient/20 Scan Card.png",
    "/images/Agnoz C-R/Patient/21 Booking Successfull.png",
    "/images/Agnoz C-R/Patient/Account Type And Pkg.png",
    "/images/Agnoz C-R/Patient/Account Type.png",
    "/images/Agnoz C-R/Patient/Adding Card.png",
    "/images/Agnoz C-R/Patient/Booking Successfull.png",
    "/images/Agnoz C-R/Patient/Categories.png",
    "/images/Agnoz C-R/Patient/Chat.png",
    "/images/Agnoz C-R/Patient/Continue Login.png",
    "/images/Agnoz C-R/Patient/Doctor Profile.png",
    "/images/Agnoz C-R/Patient/Genetic Result.png",
    "/images/Agnoz C-R/Patient/Home Page.png",
    "/images/Agnoz C-R/Patient/menu.png",
    "/images/Agnoz C-R/Patient/My Bookings.png",
    "/images/Agnoz C-R/Patient/My Booking.png",
    "/images/Agnoz C-R/Patient/My Bookings-1.png",
    "/images/Agnoz C-R/Patient/Payment Method.png",
    "/images/Agnoz C-R/Patient/Popular Doctors.png",
    "/images/Agnoz C-R/Patient/Privacy Policy.png",
    "/images/Agnoz C-R/Patient/Report Generated.png",
    "/images/Agnoz C-R/Patient/Review.png",
    "/images/Agnoz C-R/Patient/Select Time Slot.png",
    "/images/Agnoz C-R/Patient/Sign In.png",
    "/images/Agnoz C-R/Patient/Sign Up-1.png",
    "/images/Agnoz C-R/Patient/Sign Up-2.png",
    "/images/Agnoz C-R/Patient/Sign Up-3.png",
    "/images/Agnoz C-R/Patient/Sign Up-4.png",
    "/images/Agnoz C-R/Patient/Sign Up-5.png",
    "/images/Agnoz C-R/Patient/Sign Up-6.png",
    "/images/Agnoz C-R/Patient/Sign Up-7.png",
    "/images/Agnoz C-R/Patient/Sign Up-6.png",
    "/images/Agnoz C-R/Patient/Sign Up.png",
    "/images/Agnoz C-R/Patient/Splash Screen 1.png",
    "/images/Agnoz C-R/Patient/Splash Screen 2.png",
    "/images/Agnoz C-R/Patient/Splash Screen 3.png",
    "/images/Agnoz C-R/Patient/Terms & Conditions.png",
    "/images/Agnoz C-R/Patient/Terms & Conditions-1.png",

    // Doctor Screenshots
    "/images/Agnoz C-R/Doctor/Account Type.png",
    "/images/Agnoz C-R/Doctor/Add New Perceptions.png",
    "/images/Agnoz C-R/Doctor/Appointments-1.png",
    "/images/Agnoz C-R/Doctor/Appointments.png",
    "/images/Agnoz C-R/Doctor/Continue Login.png",
    "/images/Agnoz C-R/Doctor/Dashboard.png",
    "/images/Agnoz C-R/Doctor/Details.png",
    "/images/Agnoz C-R/Doctor/Details-1.png",
    "/images/Agnoz C-R/Doctor/Details-2.png",
    "/images/Agnoz C-R/Doctor/Doctor See patient profile-1.png",
    "/images/Agnoz C-R/Doctor/Doctor See patient profile-2.png",
    "/images/Agnoz C-R/Doctor/Doctor See patient profile-3.png",
    "/images/Agnoz C-R/Doctor/Doctor See patient profile.png",
    "/images/Agnoz C-R/Doctor/Edit Profile-1.png",
    "/images/Agnoz C-R/Doctor/Edit Profile.png",
    "/images/Agnoz C-R/Doctor/Genetic Result.png",
    "/images/Agnoz C-R/Doctor/Home Page.png",
    "/images/Agnoz C-R/Doctor/image 1595.png",
    "/images/Agnoz C-R/Doctor/menu.png",
    "/images/Agnoz C-R/Doctor/My Patients.png",
    "/images/Agnoz C-R/Doctor/Pharmacies.png",
    "/images/Agnoz C-R/Doctor/Report Generated.png",
    "/images/Agnoz C-R/Doctor/Settings.png",
    "/images/Agnoz C-R/Doctor/Setup Availability.png",
    "/images/Agnoz C-R/Doctor/Sign Up-1.png",
    "/images/Agnoz C-R/Doctor/Sign Up.png",

    // Business Screenshots
    "/images/Agnoz C-R/Business/Account Type.png",
    "/images/Agnoz C-R/Business/Continue Login.png",
    "/images/Agnoz C-R/Business/Details-1.png",
    "/images/Agnoz C-R/Business/Details-2.png",
    "/images/Agnoz C-R/Business/Details.png",
    "/images/Agnoz C-R/Business/Home Page.png",
    "/images/Agnoz C-R/Business/Sign Up-1.png",
    "/images/Agnoz C-R/Business/Sign Up.png",
    "/images/Agnoz C-R/Business/Splash Screen.png",
    "/images/Agnoz C-R/Business/Taking Personal Pic.png",
    "/images/Agnoz C-R/Business/When Clicked On anyitem-1.png",
    "/images/Agnoz C-R/Business/When Clicked On anyitem.png",
    
    // Employee Screenshots
    "/images/Agnoz C-R/Employee/Dashboard-1.png",
    "/images/Agnoz C-R/Employee/Dashboard-2.png",
    "/images/Agnoz C-R/Employee/Dashboard-3.png",
    "/images/Agnoz C-R/Employee/Dashboard-4.png",
    "/images/Agnoz C-R/Employee/Dashboard-5.png",
    "/images/Agnoz C-R/Employee/Dashboard-6.png",
    "/images/Agnoz C-R/Employee/Dashboard-7.png",
    "/images/Agnoz C-R/Employee/Dashboard-8.png",
    "/images/Agnoz C-R/Employee/Dashboard-9.png",
    "/images/Agnoz C-R/Employee/Dashboard-10.png",
    "/images/Agnoz C-R/Employee/Dashboard-11.png",
    "/images/Agnoz C-R/Employee/Dashboard.png",
    "/images/Agnoz C-R/Employee/Details-1.png",
    "/images/Agnoz C-R/Employee/Details-2.png",
    "/images/Agnoz C-R/Employee/Details.png",
    "/images/Agnoz C-R/Employee/Sign In-1.png",
    "/images/Agnoz C-R/Employee/Sign In.png",
    "/images/Agnoz C-R/Employee/Splash Screen.png",
    "/images/Agnoz C-R/Employee/Splash Screen-1.png",
    
];