export const babylandGallery = [
    "/images/Babyland-AI Health app/1.png",
    "/images/Babyland-AI Health app/2.png",
    "/images/Babyland-AI Health app/3.png",
    "/images/Babyland-AI Health app/4.png",
    "/images/Babyland-AI Health app/5.png",
    "/images/Babyland-AI Health app/6.png",
    "/images/Babyland-AI Health app/7.png",
    "/images/Babyland-AI Health app/8.png",
    "/images/Babyland-AI Health app/9.png",
    "/images/Babyland-AI Health app/10.png",
    "/images/Babyland-AI Health app/11.png",
    "/images/Babyland-AI Health app/12.png",
    "/images/Babyland-AI Health app/13.png",
    "/images/Babyland-AI Health app/14.png",
    "/images/Babyland-AI Health app/15.png",
    "/images/Babyland-AI Health app/16.png",
    "/images/Babyland-AI Health app/17.png",
    "/images/Babyland-AI Health app/18.png",
    "/images/Babyland-AI Health app/19.png",
    "/images/Babyland-AI Health app/20.png",
    "/images/Babyland-AI Health app/21.png",
    "/images/Babyland-AI Health app/22.png",
    "/images/Babyland-AI Health app/23.png",
    "/images/Babyland-AI Health app/24.png",
    "/images/Babyland-AI Health app/25.png",
    "/images/Babyland-AI Health app/26.png",
    "/images/Babyland-AI Health app/27.png",
    "/images/Babyland-AI Health app/28.png",
    "/images/Babyland-AI Health app/29.png",
    "/images/Babyland-AI Health app/30.png",
    "/images/Babyland-AI Health app/31.png",
    "/images/Babyland-AI Health app/32.png",
    "/images/Babyland-AI Health app/33.png",
    "/images/Babyland-AI Health app/34.png",
    "/images/Babyland-AI Health app/35.png",
    "/images/Babyland-AI Health app/36.png",
    "/images/Babyland-AI Health app/37.png",
    "/images/Babyland-AI Health app/38.png",
    "/images/Babyland-AI Health app/39.png",
    "/images/Babyland-AI Health app/40.png",
    "/images/Babyland-AI Health app/41.png",
    "/images/Babyland-AI Health app/42.png",
    "/images/Babyland-AI Health app/43.png",
    "/images/Babyland-AI Health app/44.png",
    "/images/Babyland-AI Health app/45.png",
    "/images/Babyland-AI Health app/46.png",
    "/images/Babyland-AI Health app/47.png",
    "/images/Babyland-AI Health app/48.png",
    "/images/Babyland-AI Health app/49.png",
    "/images/Babyland-AI Health app/50.png",
    "/images/Babyland-AI Health app/51.png",
    "/images/Babyland-AI Health app/52.png",
    "/images/Babyland-AI Health app/53.png",
    "/images/Babyland-AI Health app/54.png",
    "/images/Babyland-AI Health app/55.png",
    "/images/Babyland-AI Health app/56.png",
    "/images/Babyland-AI Health app/57.png",
    "/images/Babyland-AI Health app/58.png",
    "/images/Babyland-AI Health app/59.png",
    "/images/Babyland-AI Health app/60.png",
    "/images/Babyland-AI Health app/61.png",
    "/images/Babyland-AI Health app/62.png",
    "/images/Babyland-AI Health app/63.png",
    "/images/Babyland-AI Health app/64.png",
    "/images/Babyland-AI Health app/65.png",
    "/images/Babyland-AI Health app/66.png",
    "/images/Babyland-AI Health app/67.png",
    "/images/Babyland-AI Health app/68.png",
    "/images/Babyland-AI Health app/69.png",
    "/images/Babyland-AI Health app/70.png",
    "/images/Babyland-AI Health app/72.png",
    "/images/Babyland-AI Health app/73.png",
    "/images/Babyland-AI Health app/74.png",
    "/images/Babyland-AI Health app/75.png",
    "/images/Babyland-AI Health app/76.png",
    "/images/Babyland-AI Health app/77.png",
    "/images/Babyland-AI Health app/78.png",
    "/images/Babyland-AI Health app/79.png",
    "/images/Babyland-AI Health app/80.png",
    "/images/Babyland-AI Health app/81.png",
    "/images/Babyland-AI Health app/82.png",
    "/images/Babyland-AI Health app/83.png",
    "/images/Babyland-AI Health app/84.png",

    "/images/Babyland-AI Health app/AI Insights/1.png",
    "/images/Babyland-AI Health app/AI Insights/2.png",
    "/images/Babyland-AI Health app/AI Insights/3.png",
    "/images/Babyland-AI Health app/AI Insights/4.png",
    "/images/Babyland-AI Health app/AI Insights/5.png",
    "/images/Babyland-AI Health app/AI Insights/6.png",
    "/images/Babyland-AI Health app/AI Insights/7.png",
    "/images/Babyland-AI Health app/AI Insights/8.png",


    "/images/Babyland-AI Health app/Appointment/1.png",
    "/images/Babyland-AI Health app/Appointment/2.png",
    "/images/Babyland-AI Health app/Appointment/3.png",
    "/images/Babyland-AI Health app/Appointment/4.png",
    "/images/Babyland-AI Health app/Appointment/5.png",
    "/images/Babyland-AI Health app/Appointment/6.png",

    "/images/Babyland-AI Health app/Post pregnancy flow/1.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/2.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/3.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/4.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/5.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/6.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/7.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/8.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/9.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/10.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/11.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/12.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/13.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/14.png",
    "/images/Babyland-AI Health app/Post pregnancy flow/15.png",


    
];