export const doctoConGallery = [
  "/images/DoctoCon/Audio call-1.png",
  "/images/DoctoCon/Audio call.png",
  "/images/DoctoCon/Bank details.png",
  "/images/DoctoCon/Change email.png",
  "/images/DoctoCon/Chat-1.png",
  "/images/DoctoCon/Chat-2.png",
  "/images/DoctoCon/Chat-3.png",
  "/images/DoctoCon/Chat-4.png",
  "/images/DoctoCon/Chat-5.png",
  "/images/DoctoCon/Chat-6.png",
  "/images/DoctoCon/Chat.png",
  "/images/DoctoCon/Chat/copy/delete.png",
  "/images/DoctoCon/Chat/message/more-options.png",
  "/images/DoctoCon/Chat/photos-1.png",
  "/images/DoctoCon/Chat/photos-full-1.png",
  "/images/DoctoCon/Chat/photos-full-2.png",
  "/images/DoctoCon/Chat/photos-full-3.png",
  "/images/DoctoCon/Chat/photos-full.png",
  "/images/DoctoCon/Chat/photos.png",
  "/images/DoctoCon/Chat/voice-message.png",
  "/images/DoctoCon/Compliance and security.png",
  "/images/DoctoCon/Connect history-1.png",
  "/images/DoctoCon/Connect history.png",
  "/images/DoctoCon/Create account-1.png",
  "/images/DoctoCon/Create account.png",
  "/images/DoctoCon/Create account/strong password-1.png",
  "/images/DoctoCon/Create account/strong password-2.png",
  "/images/DoctoCon/Create account/strong password-3.png",
  "/images/DoctoCon/Create account/strong password.png",
  "/images/DoctoCon/Doctor Invoice.png",
  "/images/DoctoCon/Doctor profile/about-1.png",
  "/images/DoctoCon/Doctor profile/about-2.png",
  "/images/DoctoCon/Doctor profile/about-3.png",
  "/images/DoctoCon/Doctor profile/about-4.png",
  "/images/DoctoCon/Doctor profile/about-5.png",
  "/images/DoctoCon/Doctor profile/about-6.png",
  "/images/DoctoCon/Doctor profile/about.png",
  "/images/DoctoCon/Doctor profile/about/share-profile.png",
  "/images/DoctoCon/Doctor profile/review-form-1.png",
  "/images/DoctoCon/Doctor profile/review-form.png",
  "/images/DoctoCon/Doctor profile/review-form/filled.png",
  "/images/DoctoCon/Doctor profile/reviews.png",
  "/images/DoctoCon/Doctor side.png",
  "/images/DoctoCon/Doctor zone.png",
  "/images/DoctoCon/Doctors near you.png",
  "/images/DoctoCon/Doctors/filter filled.png",
  "/images/DoctoCon/Doctors/sort.png",
  "/images/DoctoCon/Edit public profile.png",
  "/images/DoctoCon/Education Details.png",
  "/images/DoctoCon/Email verification/success.png",
  "/images/DoctoCon/FAQ-1.png",
  "/images/DoctoCon/FAQ.png",
  "/images/DoctoCon/Feedback After Session.png",
  "/images/DoctoCon/First name-1.png",
  "/images/DoctoCon/First name-2.png",
  "/images/DoctoCon/First name-3.png",
  "/images/DoctoCon/First name.png",
  "/images/DoctoCon/Frame 2608512.png",
  "/images/DoctoCon/General Practitioner.png",
  "/images/DoctoCon/Gift hearts.png",
  "/images/DoctoCon/Give hearts.png",
  "/images/DoctoCon/Group 14.png",
  "/images/DoctoCon/Group 47.png",
  "/images/DoctoCon/Group 78.png",
  "/images/DoctoCon/Group 79.png",
  "/images/DoctoCon/Group 80.png",
  "/images/DoctoCon/Health Assessment/filled.png",
  "/images/DoctoCon/Heart history.png",
  "/images/DoctoCon/Home page-1.png",
  "/images/DoctoCon/Home page-2.png",
  "/images/DoctoCon/Home page.png",
  "/images/DoctoCon/Incoming call.png",
  "/images/DoctoCon/info-popup-1.png",
  "/images/DoctoCon/info-popup-2.png",
  "/images/DoctoCon/info-popup-3.png",
  "/images/DoctoCon/info-popup.png",
  "/images/DoctoCon/Log in-1.png",
  "/images/DoctoCon/Log in.png",
  "/images/DoctoCon/Lyfestyle information/filled.png",
  "/images/DoctoCon/Messages/search.png",
  "/images/DoctoCon/My Doctors-1.png",
  "/images/DoctoCon/My Doctors.png",
  "/images/DoctoCon/My friends-1.png",
  "/images/DoctoCon/My friends-2.png",
  "/images/DoctoCon/My friends.png",
  "/images/DoctoCon/My Patients.png",
  "/images/DoctoCon/Notification settings.png",
  "/images/DoctoCon/Notifications-1.png",
  "/images/DoctoCon/Notifications.png",
  "/images/DoctoCon/Notifications/Empty.png",
  "/images/DoctoCon/Notifications/swipe to delete.png",
  "/images/DoctoCon/Options.png",
  "/images/DoctoCon/OTP-1.png",
  "/images/DoctoCon/OTP.png",
  "/images/DoctoCon/Patient details.png",
  "/images/DoctoCon/Patient side.png",
  "/images/DoctoCon/Payment settings-1.png",
  "/images/DoctoCon/Payment settings.png",
  "/images/DoctoCon/Payment settings/add-card-1.png",
  "/images/DoctoCon/Payment settings/add-card.png",
  "/images/DoctoCon/Payment settings/add-card/cancel.png",
  "/images/DoctoCon/Payment settings/apple-pay/more-options-1.png",
  "/images/DoctoCon/Payment settings/apple-pay/more-options.png",
  "/images/DoctoCon/Payment settings/chosen-1.png",
  "/images/DoctoCon/Payment settings/chosen.png",
  "/images/DoctoCon/Payment settings/credit-card/more-options.png",
  "/images/DoctoCon/Payment settings/delete-card.png",
  "/images/DoctoCon/Payment settings/expired.png",
  "/images/DoctoCon/Personal data-1.png",
  "/images/DoctoCon/Personal data-2.png",
  "/images/DoctoCon/Personal data.png",
  "/images/DoctoCon/Personal data/date-picker-1.png",
  "/images/DoctoCon/Personal data/date-picker.png",
  "/images/DoctoCon/Personal info/editing-1.png",
  "/images/DoctoCon/Personal info/editing.png",
  "/images/DoctoCon/Presciption.png",
  "/images/DoctoCon/Prescription-1.png",
  "/images/DoctoCon/Prescription.png",
  "/images/DoctoCon/Pricing details.png",
  "/images/DoctoCon/Profile-1.png",
  "/images/DoctoCon/Profile.png",
  "/images/DoctoCon/Referrals-1.png",
  "/images/DoctoCon/Referrals.png",
  "/images/DoctoCon/Registration details.png",
  "/images/DoctoCon/Residential Address.png",
  "/images/DoctoCon/Review.png",
  "/images/DoctoCon/Screenshot 2025-05-20 160925.png",
  "/images/DoctoCon/Search/results.png",
  "/images/DoctoCon/Search/typing/suggestions.png",
  "/images/DoctoCon/Specialisations list.png",
  "/images/DoctoCon/Splash-1.png",
  "/images/DoctoCon/Splash.png",
  "/images/DoctoCon/TFA.png",
  "/images/DoctoCon/Verification-1.png",
  "/images/DoctoCon/Verification.png",
  "/images/DoctoCon/Video Call.png",
  "/images/DoctoCon/Video-call/chat.png",
  "/images/DoctoCon/Wallet-1.png",
  "/images/DoctoCon/Wallet-2.png",
  "/images/DoctoCon/Wallet.png",
  "/images/DoctoCon/Wellcome 1.png",
  "/images/DoctoCon/Wellcome 2.png",
  "/images/DoctoCon/Wellcome 3.png",
  "/images/DoctoCon/Wellcome 4.png",
  "/images/DoctoCon/Wellcome 5.png",
  "/images/DoctoCon/Wellcome 6.png",
  "/images/DoctoCon/Workplace details.png",
  "/images/DoctoCon/Writing pad.png",
];